### ISSUE TITLE
how to to use the plus button to add new elements in a widget

### ISSUE THREAD

**Issue by Janislav** [Adobe-Muse/MuCowDocs#18]
# Problem

I've seen in several widgets that they use a plus icon to add things in muse to there widgets. To make it more understandable see the screenshot.

![jan](https://cloud.githubusercontent.com/assets/1682130/8765956/4b4b43cc-2e26-11e5-9f08-f087e21bb74b.png)

I think that this is a option provided by the adobe muse widget engine or? The problem is that i didn't found anything about that in the official documentation :/. Can you pls fix that and maybe give me some example of how to implement that?

Thanks a lot :).

**Comment by JeffryBooher** [comment]
I'm pretty sure that the button click is handled by javascript at runtime and the content is hosted on a service so they're really just adding content to the service which is then rendered in the browser where the widget is placed using AJAX or some other dynamic content injection like JSON.  

You might look at the html that is generated from one of these widgets to see how they are doing it.  

Muse, otherwise, does not support such a feature directly which is why you couldn't find it in the documentation.

**Comment by Janislav** [comment]
**First of all, thanks for the fast reply :).** 

But i don't think, that this is handled by pure JS. The reason for this is, that the screen shot shows abode muse in edit mode and the plus icon gives the designer the possibility, to add on click a new element to the widget.

**To understand it a little better, i try to explain what kind of widget we're talking about.**

The widget has one or more tilings. Every tiling is standing for a project and has a icon and a headline. The use case now is, that the designer can extend the projects via one click on this plus icon to one new project. The designer is doing that in muse, not in browser. It's everything static, no server or backend included.

I have some widgets which are working like this. They have this + icon to add for e.x a new slide to a slideshow or something. Maybe i just looking for another kind a feature and just don't know it, but i'am quite shure that there is **NO** server or ajax or stuff include. It's just a widget.

**Comment by LoveAndCoding** [comment]
The [+] icon shown in many of the native Muse widgets is not yet possible to achieve with MuCOWs. MuCOWs are more simple embedded HTML and do not contain repeatable parts or containers like the native slideshow or composition widgets. Those may be added some day, but for now, the functionality is not there.

Other widget developers, however, get around this by breaking up the widget into pieces and having the pieces rely on eachother based on class names or ids placed in the code. Then you can simply drag out multiple parts or components to add a new "section".

**Comment by Janislav** [comment]
Ok, thanks for this great anwser. So that means it's just not possible and all widgets which are able to do this are "native" widgets probably developed by adobe?

If i want to do this, i need to split it in several mucow widgets which are interleaves in each other?  

Basically right? :)

**Comment by LoveAndCoding** [comment]
Yep, that's it exactly. If you need help or tips or tricks with that, I'd recommend asking on [the MuCOW Developer Forums](https://forums.adobe.com/community/muse/adobe_muse_mucow_development), but yes, the easiest way is to make component pieces that work together. Users have been able to work with it without to much issue so far. :)

**Comment by Janislav** [comment]
Ok thanks a lot :). Than will figure out some work around for this. Thanks for the help.
