### ISSUE TITLE
Scroll bar is not appearing the first time a widget section is expanded

### ISSUE THREAD

**Issue by jp26jp** [Adobe-Muse/MuCowDocs#27]
Also, when users use a scroll wheel (or a touchpad) to scroll down, the widget scrolls to the bottom of the section making it so that if a user isn't aware of this bug, they are missing entire sections of the widget.

**Comment by jp26jp** [comment]
This is still going on in the prerelease.

**Comment by JeffryBooher** [comment]
@jp26jp can you file this issue on pre release directly? This repo isn't monitored for issues. Thanks.

**Comment by jp26jp** [comment]
I have. Remember how I sent the video? This is just a reminder since it doesn't seem to be being looked into anymore.
