### ISSUE TITLE
Scrolling in sections jumps too bottom in Macs

### ISSUE THREAD

**Issue by jp26jp** [Adobe-Muse/MuCowDocs#29]
I'm not sure if it does this in windows, but when a user scrolls down a section with the touchpad, it jumps to the bottom of that section.

**Comment by JeffryBooher** [comment]
Would you mind reporting this issue on http://museprerelease.com? You will be able to attach a screen shot and sample widget that manifests the problem.

**Comment by jp26jp** [comment]
Of course! [Here it is](http://museprerelease.com/discussion/3993/mucow-bugs-and-performance/p1?new=1)

**Comment by JeffryBooher** [comment]
Thanks!

**Comment by jp26jp** [comment]
So I posted it but no one responded or viewed the uploaded video

**Comment by JeffryBooher** [comment]
I think they are locking down for the release so all of quality engineers are working on that. I'm familiar with the issue. It isn't Mac specific but it should be resolved once the we finish porting the OOUI to native.  Your post on muse prerelease should add a test case for the scrolling on native.

**Comment by jp26jp** [comment]
Oh, okay! Sounds good
