### ISSUE TITLE
Parralax.js muse widget

### ISSUE THREAD

**Issue by Usirinc** [Adobe-Muse/MuCowDocs#30]
Hey guys, Im looking for a paralax.js muse widget that can be customized. Any leads?

**Comment by LoveAndCoding** [comment]
You may have more luck in your search by asking on the [Adobe Muse Forums](https://forums.adobe.com/community/muse). This is repo is specifically for the documentation for the development of widgets. Filing a bug here is unlikely to be noticed by very many people, especially those who might be most helpful in pointing you towards what you're looking for.

As for finding widgets, you can check the [Adobe Muse Widget Site](http://resources.muse.adobe.com/collections/widgets) for a list of community created widgets. From there, you can search and filter by things like parallax.

Hope that helps,
Andrew

**Comment by Usirinc** [comment]
Thanks andrew, really appreciate it.

**Comment by JeffryBooher** [comment]
@viper254 I'm closing this issue since it isn't related to mucow docs.  hopefully you will have more luck finding a parallax widget on the muse widget site the @ktsashes mentioned.
